# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-account-quotas
  description: This component is responsible for requesting service quota increases
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component








